export const CHANGE_QUALIFICATION_INPUT = "CHANGE_QUALIFICATION_INPUT";
export const CHANGE_SEARCH_INPUT = "CHANGE_SEARCH_INPUT";
export const SHOW_CHECKSPELLING_DIALOG = "SHOW_CHECKSPELLING_DIALOG";
export const SEARCH_SKILL = "SEARCH_SKILL";
export const HIDE_CHECKSPELLING_DIALOG = "HIDE_CHECKSPELLING_DIALOG";
export const COPY_CORRECTED_TEXT_QUALIFICATION = "COPY_CORRECTED_TEXT_QUALIFICATION";
export const COPY_CORRECTED_TEXT_CHARACTERISTICS = "COPY_CORRECTED_TEXT_CHARACTERISTICS";
export const COPY_CORRECTED_TEXT_SKILLS = "COPY_CORRECTED_TEXT_SKILL";

